version: '3'
services:
  siglens:
    image: siglens/siglens:${SIGLENS_VERSION}
    ports:
      - "8081:8081"
      - "${UI_PORT}:5122"
    volumes:
      - "${WORK_DIR}/data:/siglens/data"
      - "${WORK_DIR}/server.yaml:/siglens/server.yaml"
    command: ["./siglens", "--config", "server.yaml"]
    environment:
      - UI_PORT=${UI_PORT}
      - WORK_DIR=${WORK_DIR}
      - SIGLENS_VERSION=${SIGLENS_VERSION}

  otel-collector:
    image: otel/opentelemetry-collector:latest  
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml  
    ports:
      - "4318:4318"
    command: ["--config=/etc/otel-collector-config.yaml"]   
